.TH "gradebook" 3 "Sat Sep 10 2016" "Version 2.0" "Gradebook Master" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gradebook \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBparse\fP (string)"
.br
.ti -1c
.RI "bool \fBterm\fP () const "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static vector< string > \fBtokenize\fP (string)"
.br
.ti -1c
.RI "static vector< string > \fBtokenize\fP (string, string)"
.br
.ti -1c
.RI "static string \fBdetokenize\fP (vector< string >, int)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Gradebook Master from the source code\&.
