.TH "section" 3 "Sat Sep 10 2016" "Version 2.0" "Gradebook Master" \" -*- nroff -*-
.ad l
.nh
.SH NAME
section \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsection\fP (string)"
.br
.ti -1c
.RI "void \fBexpell\fP (string)"
.br
.ti -1c
.RI "vector< string > \fBlookup\fP (string) const "
.br
.ti -1c
.RI "map< string, double > \fBdisplay\fP (string) const "
.br
.ti -1c
.RI "double \fBget_grade\fP (string, string)"
.br
.ti -1c
.RI "void \fBchange_grade\fP (string, string, double)"
.br
.ti -1c
.RI "void \fBdelete_grade\fP (string, string)"
.br
.ti -1c
.RI "double \fBaverage\fP (string) const "
.br
.ti -1c
.RI "map< string, double > \fBdisplay_set\fP (string) const "
.br
.ti -1c
.RI "void \fBadd_student\fP (string, string)"
.br
.ti -1c
.RI "void \fBadd_all\fP (vector< array< string, 2 > >)"
.br
.ti -1c
.RI "map< string, double > \fBall_averages\fP () const "
.br
.ti -1c
.RI "map< string, map< string, double > > \fBdisplay_all\fP () const "
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Gradebook Master from the source code\&.
