.TH "student" 3 "Sat Sep 10 2016" "Version 2.0" "Gradebook Master" \" -*- nroff -*-
.ad l
.nh
.SH NAME
student \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstudent\fP (string, string)"
.br
.ti -1c
.RI "string \fBget_name\fP () const "
.br
.ti -1c
.RI "string \fBget_first_name\fP () const "
.br
.ti -1c
.RI "string \fBget_last_name\fP () const "
.br
.ti -1c
.RI "double \fBget_grade\fP (string)"
.br
.ti -1c
.RI "void \fBchange_grade\fP (string, double)"
.br
.ti -1c
.RI "void \fBdelete_grade\fP (string)"
.br
.ti -1c
.RI "double \fBaverage\fP () const "
.br
.ti -1c
.RI "map< string, double > \fBget_grades\fP () const "
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Gradebook Master from the source code\&.
